FILE_NAMES = {
    "best_tour": "best_tour_",
    "random_tour": "random_tour_",
    "nn": "nn_",
    "nn_ite": "nn_ite_",
    "greedy": "greedy_",
    "greedy_ite": "greedy_ite_",
    "table": "table_",
    "two_opt_random": "2_opt_random_",
    "two_opt_nn": "2_opt_nn_",
    "two_opt_greedy": "2_opt_greedy_",
    "double_bridge_random": "2_bridge_random_",
    "double_bridge_nn": "2_bridge_nn_",
    "double_bridge_greedy": "2_bridge_greedy_",
    "grasp": "grasp_",
    "alpha_0": "alpha_0_",
    "alpha_0.25": "alpha_0.25_",
    "alpha_0.5": "alpha_0.5_",
    "alpha_0.75": "alpha_0.75_",
    "alpha_1": "alpha_1_",
}

LABEL_NAMES = {
    "best_tour": "Mejor camino",
    "random_tour": "Camino Aleatorio",
    "nn": "Nearest N",
    "nn_ite": "Nearest N Iterado",
    "greedy": "Greddy",
    "greedy_ite": "Greddy Iterado",
    "two_opt_random": "2-opt Aleatorio",
    "two_opt_nn": "2-opt Nearest N",
    "two_opt_greedy": "2-opt Greedy",
    "double_bridge_random": "2-bridge Aleatorio",
    "double_bridge_nn": "2-bridge Nearest N",
    "double_bridge_greedy": "2-bridge Greedy",
    "table_initial": "Camino Inicial",
    "table_local_search": "Busqueda local",
    "table_iterated_local_search": "Busqueda Local Iterativa",
    "tabu": "tabu",
    "grasp": "grasp",
    "alpha_0": "alpha 0",
    "alpha_0.25": "alpha 0.25",
    "alpha_0.5": "alpha 0.5",
    "alpha_0.75": "alpha 0.75",
    "alpha_1": "alpha 1",
    "ant_colony": "Ant Colony",
    "20": "Poblacion 20",
    "40": "Poblacion 40",
    "60": "Poblacion 60",
    "80": "Poblacion 80",
    "100": "Poblacion 100",
}
